#!/usr/bin/expect -df
#!/usr/bin/env bash

set timeout 10

set apiKey $::env(travisSCApiKey)
set username $::env(travisSCUsername)

spawn kcov coverage Travis/Scripts/travis_tronitor.sh -l

#expect "Enter your provider: "
#send -- "StatusCake\r"
expect "Selection: "
send -- "3\r"

#expect "Enter your API key: "
expect "Enter your statuscake API key:"
send -- "$apiKey\r"

#expect "Enter your username: "
expect "Enter your statuscake username:"
send -- "$username\r"

expect eof
