#!/usr/bin/expect -f
#!/usr/bin/env bash

set timeout 10

set apiKey $::env(travisApiKey)

spawn bash Travis/Scripts/travis_tronitor.sh -l

#expect "Enter your provider: "
#send -- "UptimeRobot\r"
expect "Selection: "
send -- "1\r"

#expect "Enter your API key: "
expect "Enter your uptimerobot API key:"
send -- "this-is-a-bad-api-key\r"

#expect "Enter your API key: "
expect "Enter your healthchecks API key:"
send -- "$apiKey\r"

expect eof
