#!/usr/bin/expect -f
#!/usr/bin/env bash

set timeout 10

set apiKey $::env(travisHCApiKey)

spawn bash Travis/Scripts/travis_tronitor.sh -m hc -l

#expect "Enter your provider: "
#send -- "HealthChecks\r"
#expect "Selection: "
#send -- "2\r"

#expect "Enter your API key: "
expect "Enter your Healthchecks API key:"
send -- "this-is-a-bad-api-key\r"

#expect "Enter your API key: "
expect "Enter your Healthchecks API key:"
send -- "$apiKey\r"

expect eof
